#!/usr/bin/env bash

container_name='naisten_linja_db'

if [[ $(docker ps -a -f "name=${container_name}" --format '{{.Names}}') == $container_name ]]; then
    echo "Starting container ${container_name}."
    docker start ${container_name}
else
    echo "Container $container_name not found. Creating a new one."
    docker run --name ${container_name} -e POSTGRES_USER=${DB_USERNAME} -e POSTGRES_PASSWORD=${DB_PASSWORD} -e POSTGRES_DB=${DB_NAME} -v "/$(pwd)/db-data:/var/lib/postgresql/data" -p ${DB_PORT}:5432 -d postgres:11.9
fi

tries=0
max_tries=5

until (nc -vzw 2 localhost $DB_PORT) || (($tries == 5))
do
    sleep 2
    ((tries+=1))
done

if (($tries == $max_tries)); then
    exit 1
fi
