# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow

name: CI

on:
  push

jobs:
  ci_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install --ignore-scripts --legacy-peer-deps
      - name: Run tests
        run: CI=1 npm run test
      - name: Run lint and type checks
        run: CI=1 npm run lint:node && npm run lint && npm run backend:typecheck && npm run frontend:typecheck
