# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow

name: CI

on:
  push

jobs:
  ci_run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '14.16'
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Run tests
        run: CI=1 npm run test
      - name: Test frontend builds
        run: CI=1 npm run frontend-build
      - name: Test backend builds
        run: CI=1 npm run backend-build
