# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow

name: Deploy DEV

on:
  push:
    branches:
      - master
      - test-deploy-dev # you can push to this branch to test the dev-deploy process, without having to iterate on master, potentially interfering with others' work

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12.17'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: CI=1 npm test
      - name: Deploy backend
        run: |
          heroku push -a naistenlinja-services-dev
